
# memcached
RUN apk add --no-cache --update libmemcached-libs
RUN set -xe \
    && apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
    && apk add --no-cache --update --virtual .memcached-deps zlib-dev libmemcached-dev \
    && pecl install memcached \
    && apk del .memcached-deps .phpize-deps

RUN rm -rf /tmp/*
