services:

  php:
    build: docker/php
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
    environment:
      - APP_DEBUG=true
      - APP_NAME=PROJECT_NAME (local)

  node:
    image: node:current-alpine
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
